[project]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "CSV files that adheres closely to the Python standard library's csv module"
name = "csv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = { cmd = "rattler-build build --recipe recipes -c https://conda.modular.com/max-nightly -c conda-forge --skip-existing=all", env = {MODULAR_MOJO_IMPORT_PATH = "$CONDA_PREFIX/lib/mojo"} }
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY", CONDA_BLD_PATH = "output" } }

[dependencies]
max = ">=24.6.0.dev2024101605, <=25"
